language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer update --prefer-dist --no-interaction

script:
  - php test/test.php

after_script:
  - if [ $(phpenv version-name) = "7.3" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ $(phpenv version-name) = "7.3" ]; then php ocular.phar code-coverage:upload --format=php-clover test/clover.xml; fi
